import type { Evidence } from '../documents/evidence'
import { money } from '../documents/evidence'
import { assessPhone, RULE_VERSION, sources, type PhoneAnswers } from './phone'
const escape = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]!)
const labels: Record<keyof PhoneAnswers, string> = { kind: 'Payment type', payer: 'Cost incurred and paid by', use: 'Work-use purpose', homeMethod: 'Working-from-home method', elsewhere: 'Already included elsewhere', records: 'Supplier bill and 4-week record checked', representative: 'Percentage representative of this bill', reimbursedAmount: 'Amount reimbursed (AUD)' }
export function assessmentHtml(item: Evidence, evidence: Evidence[], counted: boolean, now: Date, credits: Evidence[]) {
  if (!item.phone) return '<h3>Phone assessment</h3><p>Not started. No assessment amount.</p>'
  const result = assessPhone(item, evidence, counted, '2025-26', now, sources, credits)
  return `<h3>Draft phone assessment</h3><p>${escape(result.reviewGate)} Rule: ${escape(result.ruleVersion)}. Source collection: ${escape(result.sourceVersion)}.</p><p>Status: ${escape(result.status)}. ${result.cents === null ? 'No amount calculated.' : `Illustrative separate work portion: ${money(result.cents)}.`}</p>${result.calculation ? `<p>${escape(result.calculation)}</p>` : ''}<p>One bill only; no annual extrapolation, handset calculation, income, withholding, refund or complete return. User confirmations are not independently verified. Extraction confidence is not tax eligibility.</p><h4>Additional user confirmations</h4><ul>${Object.entries(item.phone).map(([key, value]) => `<li>${labels[key as keyof PhoneAnswers]}: ${escape(value || 'Unanswered')}</li>`).join('')}</ul><h4>Conditions and unresolved questions</h4><ul>${result.findings.map(finding => `<li>${escape(finding.message)} ${finding.sources.map(id => { const source = sources.find(source => source.id === id)!; return `<a href="${escape(source.url)}">ATO: ${escape(source.title)}</a>` }).join(' · ')}</li>`).join('')}</ul>`
}
export function sourceRegisterHtml() {
  return `<h2>ATO source register</h2><p>Rule ${RULE_VERSION}. All applicability mappings and expected examples await qualified tax review. No reviewer or review date assigned. Retrieved material is not professional approval. Captured source checks expire after 180 days under project policy; no live source search is performed.</p>${sources.map(source => `<section><h3><a href="${escape(source.url)}">${escape(source.title)}</a></h3><p>QC ${source.qc}; applicable year 2025–26 (provisional). Page updated ${source.updatedAt}; retrieved ${source.retrievedAt}; review pending.<br>SHA-256 <code>${source.sha256}</code><br>Mapped conditions: ${escape(source.conditions.join(', '))}</p></section>`).join('')}`
}
