import { aud, fields, labels, totals, observations, confirmationIssues, PAYSLIP_VERSION, type Payslip } from './payslip'
const escape = (v: unknown) => String(v ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]!))
export function payslipReport(selected: Payslip[], all: Payslip[], scope: string): string {
  const t = totals(selected), pending = all.filter(s => !s.confirmed || confirmationIssues(s, all).length)
  return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>TaxPrep AU pay history</title><style>body{max-width:1000px;margin:40px auto;padding:0 20px;font:16px/1.6 system-ui;color:#173f35}table{width:100%;border-collapse:collapse}td,th{padding:8px;border-bottom:1px solid #ddd;text-align:left;overflow-wrap:anywhere}pre{white-space:pre-wrap;overflow-wrap:anywhere}section{margin:30px 0}@media print{body{font-size:10px}}@media(max-width:650px){table{font-size:11px}td,th{padding:4px}}</style><h1>TaxPrep AU pay history</h1><p>${escape(scope)}. ${selected.length} confirmed records. ${all.some(s => s.sample) ? 'Fictional example data.' : 'User-supplied records.'}</p><p>Gross ${aud(t.gross)} · Withheld ${aud(t.withheld)} · Other deductions ${aud(t.deductions)} · Net ${aud(t.net)}. Withheld share of gross: ${t.percentage ?? 'unavailable'}${t.percentage === null ? '' : '%'}.</p><p>Super recorded: ${t.superKnown ? aud(t.superCents) : 'unknown'} (${t.superKnown}/${t.count} records supplied an amount). This is not a fund balance or proof of payment.</p><p>These are confirmed period figures only. Missing pays are not inferred and cumulative YTD figures are not added. Confirmation means the user checked data entry, not that tax, wages or employer remittances are correct. No refund forecast, award audit or tax-return lodgment is included. Parser ${PAYSLIP_VERSION}.</p><h2>Things to check</h2><ul>${observations(selected).map(n => `<li>${escape(n)}</li>`).join('')}</ul><h2>Confirmed records in selected view</h2>${selected.map(s => `<section><h3>${escape(s.facts.employer)} · ${escape(s.facts.payDate)}</h3><p>Source ${escape(s.name)} · ${s.hash ? 'Page 1 · SHA-256 ' + escape(s.hash) : 'Manual entry; no document attached'}</p><table><tr><th>Field</th><th>Original extraction</th><th>Confirmed value</th></tr>${fields.map(k => `<tr><th>${labels[k]}</th><td>${escape(s.original[k]) || 'Not supplied'}</td><td>${escape(s.facts[k]) || 'Unknown'}</td></tr>`).join('')}</table></section>`).join('')}<h2>Outstanding reviews across the session</h2><p>${pending.length} record(s) excluded from totals. This list is not restricted by the selected filters.</p><ul>${pending.map(s => `<li>${escape(s.name)}: ${escape(confirmationIssues(s, all).join(' ') || 'User confirmation needed.')}</li>`).join('')}</ul><p>Original PDFs and complete extracted text are not embedded. Keep original documents separately. Downloaded reports remain on your device.</p></html>`
}
export function downloadPayReport(html: string) {
  const url = URL.createObjectURL(new Blob([html], { type: 'text/html' })), a = document.createElement('a')
  a.href = url; a.download = 'taxprep-pay-history.html'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000)
}
