// @vitest-environment jsdom
import { afterEach, expect, it, vi } from 'vitest'
import { act, cleanup, render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import '@testing-library/jest-dom/vitest'
import GuidedDemo from '../demo/GuidedDemo'
import { sampleExpenses } from '../expenses/expenseReview'
import { createExpenseDraft } from '../expenses/expenseDraft'
import { encodeProgress, parseProgress, PROGRESS_KEY } from './progressStorage'

const button = (name: string) => screen.getByRole('button', { name })
const saved = () => encodeProgress({ expenses: sampleExpenses, step: { kind: 'summary' } }, new Date('2026-09-17T08:00:00.000Z'))
afterEach(() => { cleanup(); vi.restoreAllMocks(); vi.unstubAllGlobals(); localStorage.clear() })

it('saves an unfinished form explicitly, restores it and keeps typing focus', async () => {
  vi.stubGlobal('fetch', vi.fn())
  const user = userEvent.setup(); const first = render(<GuidedDemo />)
  await user.click(button('Try demo')); await user.click(button('Information is correct'))
  await user.click(screen.getByRole('button', { name: /^Yes/ }))
  await user.type(screen.getByLabelText('Amount paid (AUD)'), '12.')
  expect(screen.getByLabelText('Amount paid (AUD)')).toHaveFocus()
  await user.type(screen.getByLabelText(/Work purpose/), 'Notes to finish')
  expect(localStorage.getItem(PROGRESS_KEY)).toBeNull()
  await user.click(button('Save progress'))
  const raw = localStorage.getItem(PROGRESS_KEY)!
  expect(parseProgress(raw).data.step.kind).toBe('details')
  expect(screen.getByText('This progress is saved.')).toBeVisible()
  await user.type(screen.getByLabelText(/Work purpose/), ' later')
  expect(localStorage.getItem(PROGRESS_KEY)).toBe(raw)
  expect(button('Save progress')).toBeEnabled()
  first.unmount(); render(<GuidedDemo />)
  expect(screen.getByRole('heading', { name: 'Meet Sarah' })).toBeVisible()
  await user.click(button('Resume saved progress'))
  expect(screen.getByLabelText('Amount paid (AUD)')).toHaveValue('12.')
  expect(screen.getByLabelText(/Work purpose/)).toHaveValue('Notes to finish')
  expect(screen.getByRole('heading', { name: 'Transport fares details' })).toHaveFocus()
  await user.click(button('Save expense'))
  expect(screen.getByLabelText('Amount paid (AUD)')).toHaveAttribute('aria-invalid', 'true')
  expect(fetch).not.toHaveBeenCalled()
})
it('restores an edit separately from its committed record and rechecks the summary after cancel', async () => {
  const fields = { ...createExpenseDraft(sampleExpenses[1]), amount: '999' }
  localStorage.setItem(PROGRESS_KEY, encodeProgress({ expenses: sampleExpenses, step: { kind: 'details', category: 'phone', index: 0, returnTo: 'summary', fields } }))
  const fetch = vi.fn().mockReturnValue(new Promise(() => {})); vi.stubGlobal('fetch', fetch)
  const user = userEvent.setup(); render(<GuidedDemo />)
  await user.click(button('Resume saved progress'))
  expect(screen.getByLabelText('Amount paid (AUD)')).toHaveValue('999')
  expect(fetch).not.toHaveBeenCalled()
  await user.click(button('Cancel changes'))
  expect(screen.getByText('$600.00 × 40% work use')).toBeVisible()
  expect(fetch).toHaveBeenCalledOnce()
  expect(screen.getByText('Reviewing your expense details…')).toBeVisible()
  expect(screen.queryByRole('button', { name: 'Download report (HTML)' })).not.toBeInTheDocument()
})
it('keeps invalid storage intact until deletion and preserves unrelated keys', async () => {
  localStorage.setItem(PROGRESS_KEY, '{broken'); localStorage.setItem('another-app', 'keep')
  const user = userEvent.setup(); render(<GuidedDemo />)
  expect(screen.getByRole('alert')).toHaveTextContent('invalid')
  expect(button('Save progress')).toBeDisabled()
  await user.click(button('Try demo'))
  await user.click(button('Delete saved progress'))
  expect(screen.getByRole('heading', { name: 'Confirm Sarah’s income' })).toBeVisible()
  expect(localStorage.getItem(PROGRESS_KEY)).toBeNull()
  expect(localStorage.getItem('another-app')).toBe('keep')
  expect(button('Save progress')).toBeEnabled()
})
it('keeps work and an existing snapshot after quota failure and allows retry', async () => {
  const user = userEvent.setup(); render(<GuidedDemo />)
  await user.click(button('Try demo')); await user.click(button('Save progress'))
  const original = localStorage.getItem(PROGRESS_KEY)
  await user.click(button('Information is correct'))
  vi.spyOn(Storage.prototype, 'setItem').mockImplementationOnce(() => { throw new DOMException('full', 'QuotaExceededError') })
  await user.click(button('Save progress'))
  expect(screen.getByRole('alert')).toHaveTextContent('could not be saved')
  expect(localStorage.getItem(PROGRESS_KEY)).toBe(original)
  expect(screen.getByRole('heading', { name: /Did Sarah pay transport/ })).toBeVisible()
  await user.click(button('Save progress'))
  expect(parseProgress(localStorage.getItem(PROGRESS_KEY)!).data.step.kind).toBe('questions')
})
it('recovers from blocked reads without preventing the interview', async () => {
  const get = vi.spyOn(Storage.prototype, 'getItem').mockImplementation(() => { throw new DOMException('blocked', 'SecurityError') })
  const user = userEvent.setup(); render(<GuidedDemo />)
  expect(screen.getByRole('alert')).toHaveTextContent('unavailable')
  await user.click(button('Try demo'))
  expect(screen.getByRole('heading', { name: 'Confirm Sarah’s income' })).toBeVisible()
  get.mockRestore(); await user.click(button('Check saved progress'))
  await user.click(button('Save progress'))
  expect(localStorage.getItem(PROGRESS_KEY)).not.toBeNull()
})
it('detects a newer copy even before its storage event arrives, without overwriting it', async () => {
  const user = userEvent.setup(); render(<GuidedDemo />)
  await user.click(button('Try demo'))
  const newer = saved(); localStorage.setItem(PROGRESS_KEY, newer)
  await user.click(button('Save progress'))
  expect(localStorage.getItem(PROGRESS_KEY)).toBe(newer)
  expect(screen.getByRole('alert')).toHaveTextContent('changed')
  expect(screen.getByRole('heading', { name: 'Confirm Sarah’s income' })).toBeVisible()
  const newest = encodeProgress({ expenses: [], step: { kind: 'questions', index: 1 } })
  localStorage.setItem(PROGRESS_KEY, newest)
  await user.click(button('Delete saved progress'))
  expect(localStorage.getItem(PROGRESS_KEY)).toBe(newest)
  await user.click(button('Delete saved progress'))
  expect(localStorage.getItem(PROGRESS_KEY)).toBeNull()
})
it('reacts to another tab and never auto-resurrects its deleted copy', async () => {
  const user = userEvent.setup(); render(<GuidedDemo />)
  await user.click(button('Try demo')); await user.click(button('Save progress'))
  localStorage.removeItem(PROGRESS_KEY)
  await act(async () => window.dispatchEvent(new StorageEvent('storage', { key: PROGRESS_KEY, newValue: null })))
  expect(screen.getByText(/changed in another tab/)).toBeVisible()
  expect(button('Save progress')).toBeDisabled()
  expect(localStorage.getItem(PROGRESS_KEY)).toBeNull()
  await user.click(button('Check saved progress')); await user.click(button('Save progress'))
  expect(localStorage.getItem(PROGRESS_KEY)).not.toBeNull()
})
it('preserves memory when restart cannot delete, then clears both on successful retry', async () => {
  localStorage.setItem(PROGRESS_KEY, saved())
  vi.stubGlobal('fetch', vi.fn().mockReturnValue(new Promise(() => {})))
  const user = userEvent.setup(); render(<GuidedDemo />)
  await user.click(button('Resume saved progress'))
  const remove = vi.spyOn(Storage.prototype, 'removeItem').mockImplementation(() => { throw new Error('blocked') })
  await user.click(button('Restart demo'))
  expect(screen.getByText('$600.00 × 40% work use')).toBeVisible()
  expect(screen.getByRole('alert')).toHaveTextContent('could not be deleted')
  remove.mockRestore(); await user.click(button('Restart demo'))
  expect(localStorage.getItem(PROGRESS_KEY)).toBeNull()
  expect(screen.getByRole('heading', { name: 'Meet Sarah' })).toBeVisible()
})
