import assert from 'node:assert/strict';
import { readFileSync, writeFileSync } from 'node:fs';
export async function verifyPayslips(context, base, artifacts) {
  const page = await context.newPage(), errors = [], requests = [];
  page.on('pageerror', e => errors.push(e.message)); page.on('request', r => requests.push({ url: r.url(), method: r.method() }));
  const button = name => page.getByRole('button', { name, exact: true });
  const totals = () => page.locator('.pay-metrics strong').allTextContents();
  const examples = JSON.parse(readFileSync(new URL('../../../sample-data/payslips/examples.json', import.meta.url), 'utf8'));
  const file = (index, name) => ({ name: name || examples[index].name, mimeType: 'application/pdf', buffer: Buffer.from(examples[index].pdfBase64, 'base64') });
  try {
    await page.goto(base.href); await page.getByRole('heading', { name: 'Every payday, a clearer picture.', exact: true }).waitFor();
    await page.screenshot({ path: artifacts + 'payslip-landing-desktop.png', fullPage: true });
    await button('Try example payslips').click(); await page.getByRole('status').filter({ hasText: 'Six fictional payslips loaded.' }).waitFor();
    assert.deepEqual(await totals(), ['$10,450.00', '$8,815.00', '$1,555.00', '$1,110.00']);
    assert.equal(await page.locator('.pay-charts svg').count(), 3);
    assert.ok((await page.locator('.pay-metrics').innerText()).includes('5/6 records'));
    await page.getByLabel('Chart grouping', { exact: true }).selectOption('payday');
    await page.getByText('View exact chart figures', { exact: true }).click(); assert.equal(await page.locator('.statement-help table tbody tr').count(), 6);
    await page.getByLabel('Employer', { exact: true }).selectOption('garden example studio'); assert.deepEqual(await totals(), ['$2,200.00', '$1,960.00', '$240.00', '$120.00']);
    await page.getByLabel('Employer', { exact: true }).selectOption('all'); await page.getByLabel('Chart grouping', { exact: true }).selectOption('month');
    await page.getByText('View exact chart figures', { exact: true }).click();
    await page.screenshot({ path: artifacts + 'payslip-dashboard-desktop.png', fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 }); assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.screenshot({ path: artifacts + 'payslip-dashboard-mobile.png', fullPage: true });
    await page.setViewportSize({ width: 1440, height: 1000 }); await button('Clear pay history').click();
    await page.getByLabel('Choose payslip PDFs', { exact: true }).setInputFiles([file(0), file(1)]);
    await page.getByRole('status').filter({ hasText: '2 payslip(s) read.' }).waitFor();
    assert.deepEqual(await totals(), ['$0.00', '$0.00', '$0.00', 'Unknown']);
    await button('Confirm these figures').click(); assert.deepEqual(await totals(), ['$1,800.00', '$1,530.00', '$250.00', '$216.00']);
    await page.getByRole('button', { name: 'Review example-pay-2.pdf 2026-07-30', exact: true }).click(); await button('Confirm these figures').click();
    assert.deepEqual(await totals(), ['$3,900.00', '$3,270.00', '$590.00', '$468.00']);
    await page.getByLabel('Choose payslip PDFs', { exact: true }).setInputFiles(file(0, 'renamed.pdf')); await page.getByRole('alert').filter({ hasText: 'already added' }).waitFor(); assert.equal(await page.locator('.pay-history tbody tr').count(), 2);
    await page.getByLabel('Choose payslip PDFs', { exact: true }).setInputFiles([{ name: 'bad.pdf', mimeType: 'application/pdf', buffer: Buffer.from('not a pdf') }, file(2)]); await page.getByRole('alert').filter({ hasText: 'not a PDF' }).waitFor(); assert.equal(await page.locator('.pay-history tbody tr').count(), 2);
    await page.getByRole('button', { name: 'Review example-pay-1.pdf 2026-07-16', exact: true }).click();
    await page.getByLabel('Tax withheld (AUD)', { exact: true }).fill(''); assert.deepEqual(await totals(), ['$2,100.00', '$1,740.00', '$340.00', '$252.00']); assert.equal(await button('Confirm these figures').isDisabled(), true);
    await page.getByLabel('Tax withheld (AUD)', { exact: true }).fill('260'); await page.getByLabel('Net pay (AUD)', { exact: true }).fill('1520'); await button('Confirm these figures').click();
    assert.deepEqual(await totals(), ['$3,900.00', '$3,260.00', '$600.00', '$468.00']);
    await button('Enter figures manually').click();
    await page.locator('.pay-review').getByLabel('Employer', { exact: true }).fill('Manual example');
    for (const [label, value] of [['Period start', '2026-06-01'], ['Period end', '2026-06-14'], ['Pay date', '2026-06-16'], ['Gross pay (AUD)', '100'], ['Tax withheld (AUD)', '0'], ['Other deductions (AUD)', '0'], ['Net pay (AUD)', '100']]) await page.locator('.pay-review').getByLabel(label, { exact: true }).fill(value);
    await button('Confirm these figures').click(); await page.getByLabel('Financial year', { exact: true }).selectOption('2025–26'); assert.deepEqual(await totals(), ['$100.00', '$100.00', '$0.00', 'Unknown']);
    const downloadEvent = page.waitForEvent('download'); await button('Download pay report').click(); const download = await downloadEvent; await download.saveAs(artifacts + 'pay-history.html');
    const report = readFileSync(artifacts + 'pay-history.html', 'utf8'); assert.ok(report.includes('Manual example')); assert.ok(!report.includes('Harbour Example Services')); assert.ok(report.includes('No refund forecast'));
    await page.getByLabel('Financial year', { exact: true }).selectOption('all');
    const allDownloadEvent = page.waitForEvent('download'); await button('Download pay report').click(); await (await allDownloadEvent).saveAs(artifacts + 'pay-history-all.html');
    const allReport = readFileSync(artifacts + 'pay-history-all.html', 'utf8'); assert.ok(allReport.includes('250.00')); assert.ok(allReport.includes('260')); assert.ok(allReport.includes('SHA-256'));
    await page.setViewportSize({ width: 390, height: 844 }); await page.getByRole('button', { name: 'Review Manual payslip 2026-06-16', exact: true }).click(); assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.screenshot({ path: artifacts + 'payslip-review-mobile.png', fullPage: true }); await button('Remove this payslip').click(); assert.equal(await page.locator('.pay-history tbody tr').count(), 2);
    await button('Statement analysis').click(); await button('Payslip dashboard').click(); assert.equal(await page.locator('.pay-metrics').count(), 0);
    await button('Try example payslips').click(); await page.getByRole('status').filter({ hasText: 'Six fictional payslips loaded.' }).waitFor(); await page.reload(); await page.getByRole('heading', { name: 'Every payday, a clearer picture.' }).waitFor(); assert.equal(await page.locator('.pay-metrics').count(), 0);
    assert.deepEqual(await page.evaluate(() => Object.keys(localStorage).filter(k => /payslip/i.test(k))), []);
    assert.deepEqual(errors, []); assert.ok(requests.every(r => r.method === 'GET')); assert.ok(requests.every(r => r.url.startsWith(base.origin) || r.url.startsWith('blob:') || r.url.startsWith('data:')));
    const result = { passed: true, samplePdfs: 6, grossAud: 10450, netAud: 8815, withheldAud: 1555, knownSuperAud: 1110, superCoverage: '5/6', unconfirmedExcluded: true, correctionInvalidates: true, duplicateBlocked: true, badBatchAtomic: true, manualEntry: true, yearAndEmployerFilters: true, chartGroups: true, offlineExport: true, clearRefreshAndWorkspaceChange: true, mobileOverflow: false, documentUploads: 0, modelRequests: 0, pageErrors: errors };
    writeFileSync(artifacts + 'payslip-evaluation.json', JSON.stringify(result, null, 2)); return result;
  } catch (e) { await page.screenshot({ path: artifacts + 'payslip-failure.png', fullPage: true }); console.error((await page.locator('body').innerText()).slice(-10000)); throw e } finally { await page.close() }
}
