import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

// Called inside the real document flow, after the linked $18 phone illustration.
export async function verifyPreparation(page, artifacts) {
  const button = name => page.getByRole('button', { name, exact: true });
  await button('Preparation summary').click();
  const workspace = page.getByRole('region', { name: 'Put the whole picture in one place.' });
  const amounts = () => workspace.locator('.preparation-totals strong').allTextContents();
  assert.deepEqual(await amounts(), ['Not reviewed', 'Not reviewed', '$18.00']);
  await button('Load fictional income example').click();
  assert.equal(await button('Load fictional income example').isDisabled(), true);
  assert.equal(await workspace.locator('.income-card').count(), 3);
  assert.deepEqual(await amounts(), ['Not reviewed', 'Not reviewed', '$18.00']);
  for (let i = 0; i < 3; i++) await workspace.locator('.income-card').nth(i).getByRole('button', { name: 'Confirm income record', exact: true }).click();
  assert.deepEqual(await amounts(), ['$82,150.00', '$17,100.00', '$18.00']);
  const first = workspace.getByRole('article', { name: 'Income record 1', exact: true });
  await first.getByLabel('Gross income (AUD)', { exact: true }).fill('65000');
  assert.deepEqual(await amounts(), ['$18,150.00', '$3,600.00', '$18.00']);
  await first.getByRole('button', { name: 'Confirm income record', exact: true }).click();
  assert.deepEqual(await amounts(), ['$83,150.00', '$17,100.00', '$18.00']);
  await button('Add salary record').click();
  const fourth = workspace.getByRole('article', { name: 'Income record 4', exact: true });
  await fourth.getByLabel('Employer name', { exact: true }).fill('Harbour Services (fictional)');
  await fourth.getByLabel('Source reference', { exact: true }).fill('Another annual record to check');
  await fourth.getByLabel('Gross income (AUD)', { exact: true }).fill('64000');
  await fourth.getByLabel('Tax withheld (AUD)', { exact: true }).fill('13500');
  await fourth.getByLabel('Is the annual source finalised?', { exact: true }).selectOption('yes');
  assert.equal(await button('These are separate income records').isDisabled(), true);
  await fourth.getByRole('button', { name: 'Confirm income record', exact: true }).click();
  assert.deepEqual(await amounts(), ['$18,150.00', '$3,600.00', '$18.00']);
  await button('These are separate income records').click();
  assert.deepEqual(await amounts(), ['$147,150.00', '$30,600.00', '$18.00']);
  await fourth.getByLabel('Gross income (AUD)', { exact: true }).fill('64001');
  assert.deepEqual(await amounts(), ['$18,150.00', '$3,600.00', '$18.00']);
  await button('Remove income record 4').click();
  assert.deepEqual(await amounts(), ['$83,150.00', '$17,100.00', '$18.00']);
  await first.getByLabel('Statement year', { exact: true }).selectOption('other');
  assert.equal(await first.getByRole('button', { name: 'Confirm income record', exact: true }).isDisabled(), true);
  assert.deepEqual(await amounts(), ['$18,150.00', '$3,600.00', '$18.00']);
  await first.getByLabel('Statement year', { exact: true }).selectOption('2025-26');
  await first.getByLabel('Tax withheld (AUD)', { exact: true }).fill('');
  assert.equal(await first.getByRole('button', { name: 'Confirm income record', exact: true }).isDisabled(), true);
  await first.getByLabel('Tax withheld (AUD)', { exact: true }).fill('0');
  await first.getByRole('button', { name: 'Confirm income record', exact: true }).click();
  assert.deepEqual(await amounts(), ['$83,150.00', '$3,600.00', '$18.00']);
  await first.getByLabel('Tax withheld (AUD)', { exact: true }).fill('13500');
  await first.getByRole('button', { name: 'Confirm income record', exact: true }).click();
  const interest = workspace.getByRole('article', { name: 'Income record 3', exact: true });
  await interest.getByLabel('Are you the sole account owner?', { exact: true }).selectOption('no');
  assert.deepEqual(await amounts(), ['$83,000.00', '$17,100.00', '$18.00']);
  await interest.getByLabel('Are you the sole account owner?', { exact: true }).selectOption('yes');
  await interest.getByRole('button', { name: 'Confirm income record', exact: true }).click();
  await workspace.getByLabel('Have you added all salary/wage and Australian bank-interest records?', { exact: true }).selectOption('yes');
  await workspace.getByText('2. Situation and coverage', { exact: true }).click();
  await workspace.getByLabel('Any income beyond salary, wages and Australian bank interest?', { exact: true }).selectOption('yes');
  await workspace.getByLabel('A HELP, VSL, AASL or other study or training loan?', { exact: true }).selectOption('unsure');
  await workspace.getByLabel('Handover notes', { exact: true }).fill('Fictional rental income needs review. <script>alert(1)</script>');
  const gaps = workspace.locator('.preparation-gaps');
  assert.ok((await gaps.innerText()).includes('Other income sections remain unprepared'));
  assert.ok((await gaps.innerText()).includes('Unsure — needs review'));
  await workspace.getByText('2. Situation and coverage', { exact: true }).click();
  await workspace.locator('.preparation-totals').screenshot({ path: artifacts + 'preparation-totals-desktop.png' });
  await first.screenshot({ path: artifacts + 'preparation-income-desktop.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await workspace.locator('.preparation-totals').screenshot({ path: artifacts + 'preparation-totals-mobile.png' });
  await first.screenshot({ path: artifacts + 'preparation-income-mobile.png' });
  const downloadEvent = page.waitForEvent('download'); await button('Download preparation handover').click();
  const download = await downloadEvent; assert.equal(download.suggestedFilename(), 'taxprep-preparation-2025-26.html');
  await download.saveAs(artifacts + 'combined-preparation-handover.html');
  const html = readFileSync(artifacts + 'combined-preparation-handover.html', 'utf8');
  for (const value of ['$83,150.00', '$17,100.00', '$18.00', '$64,000.00', 'Original sample values', 'Other income sections remain unprepared', 'Unsure', 'sample-bank.csv', 'sample-phone-receipt.pdf', 'employee-phone-2025-26.v1-draft', 'preparation-2025-26.v1', 'not ready to lodge', '&lt;script&gt;']) assert.ok(html.includes(value), value);
  assert.ok(!html.includes('<script>'));
  const offline = await page.context().newPage(); const network = [];
  offline.on('request', request => { if (/^https?:/.test(request.url())) network.push(request.url()); });
  await offline.goto('file://' + artifacts + 'combined-preparation-handover.html');
  await offline.getByRole('heading', { name: 'TaxPrep AU preparation handover', exact: true }).waitFor();
  assert.equal(await offline.locator('script').count(), 0); assert.deepEqual(network, []);
  await offline.close();
  await page.setViewportSize({ width: 1440, height: 1000 });
  await button('Documents').click();
  return { passed: true, initialGrossAud: 82150, initialWithheldAud: 17100, correctedGrossAud: 83150, illustrativePhoneAud: 18, blankNotZero: true, duplicateAndYearBlocking: true, editsInvalidateReview: true, unsupportedAndUnknownVisible: true, offlineHandover: true, mobileOverflow: false };
}
