import { money, type Evidence, type EvidenceLink } from '../documents/evidence'
import type { DocumentSource } from '../documents/documentReader'
import { downloadEvidenceReport } from '../documents/evidenceReport'
import IncomeEditor from './IncomeEditor'
import { preparationSummary, samplePreparation, situationQuestions, type Answer, type Preparation } from './preparation'
import { preparationReport } from './preparationReport'
import './preparation.css'
interface Props { value: Preparation; onChange: (value: Preparation) => void; records: Evidence[]; links: EvidenceLink[]; separate: string[]; sources: DocumentSource[]; importIssues: string[]; onDocuments: () => void; onMessage: (message: string) => void; busy: boolean }
export default function PreparationWorkspace({ value, onChange, records, links, separate, sources, importIssues, onDocuments, onMessage, busy }: Props) {
  const summary = preparationSummary(value, records, links, separate, importIssues)
  const canSample = !value.income.length && !value.incomeComplete && !value.notes && Object.values(value.situation).every(answer => !answer)
  return <section className="preparation-workspace" aria-labelledby="preparation-title">
    <div className="workspace-heading"><div><p className="eyebrow">2025–26 · Preparation handover</p><h3 id="preparation-title">Put the whole picture in one place.</h3><p>Record income, review your situation, and carry the document evidence into one handover.</p></div><span className="demo-badge">Draft · review required</span></div>
    <div className="preparation-totals" aria-label="Recorded preparation totals">
      <div><span>Recorded gross income</span><strong>{summary.income.included ? money(summary.income.grossCents) : 'Not reviewed'}</strong><small>{summary.income.included} of {value.income.length} income records included · {summary.income.complete ? 'income list confirmed' : 'partial subtotal'}</small></div>
      <div><span>Recorded tax withheld</span><strong>{summary.income.included ? money(summary.income.withheldCents) : 'Not reviewed'}</strong><small>Already withheld · not a refund estimate</small></div>
      <div><span>Illustrative phone work portions</span><strong>{summary.illustrationCount ? money(summary.illustrativeCents) : 'Not assessed'}</strong><small>{summary.illustrationCount} draft illustration{summary.illustrationCount === 1 ? '' : 's'} · not approved deductions</small></div>
    </div>
    <p className="document-warning">This is a preparation handover. Taxable income, tax, Medicare, offsets, loan repayments and a refund/payable estimate have not been calculated. Answering every question does not make a complete return.</p>
    <div className="preparation-sample"><button className="secondary-button" disabled={!canSample} onClick={() => onChange(samplePreparation())}>Load fictional income example</button><p>Two employers and one interest statement, with fictional circumstances. Supplied answers are labelled sample data and need your review. No ATO pre-fill connection. Loading is available only in an empty preparation.</p></div>
    <details className="preparation-step" open><summary>1. Income and tax withheld</summary><IncomeEditor value={value} onChange={onChange} /></details>
    <details className="preparation-step"><summary>2. Situation and coverage</summary><p>These answers identify sections that still need work. They do not calculate eligibility or replace a complete tax interview.</p><div className="evidence-form">{situationQuestions.map(question => <label key={question.key}>{question.label}<select aria-label={question.label} value={value.situation[question.key]} onChange={event => onChange({ ...value, situation: { ...value.situation, [question.key]: event.target.value as Answer } })}><option value="">Choose an answer</option><option value="yes">Yes</option><option value="no">No</option><option value="unsure">Unsure</option></select><span className="field-help">{question.help}</span></label>)}</div><label className="preparation-notes">Handover notes<textarea maxLength={2000} rows={4} value={value.notes} placeholder="For example: fictional rental income needs separate preparation." onChange={event => onChange({ ...value, notes: event.target.value })} /></label></details>
    <details className="preparation-step"><summary>3. Linked expense evidence ({summary.expenses.length} items)</summary><p>Updates automatically when documents, matches or work details change. Gross spending and draft work portions are different amounts.</p>{summary.expenses.map(group => <div className="preparation-expense" key={group.item.id}><h4>{group.item.facts.merchant || 'Unresolved expense'}</h4><p>{group.evidence.map(item => `${item.fileName} · ${item.location}`).join(' + ')}</p><p>{group.item.excluded ? `Excluded: ${group.item.excluded}` : group.assessment?.status === 'illustration' ? `${money(group.assessment.cents!)} illustrative work portion · review pending` : group.assessment?.status === 'no-separate-amount' ? 'Draft: no separate phone amount · review pending' : 'Needs evidence or assessment review'}</p></div>)}<button className="secondary-button" onClick={onDocuments}>Review documents and expenses</button></details>
    <section className="preparation-gaps" aria-labelledby="preparation-gaps-title"><h4 id="preparation-gaps-title">What still needs attention ({summary.gaps.length})</h4><ul>{summary.gaps.map((gap, index) => <li key={`${gap.section}-${index}`}><strong>{gap.section}</strong><span>{gap.message}</span></li>)}</ul></section>
    <div className="evidence-export"><h4>Download one preparation handover</h4><p>Includes income records, original sample values, circumstances, coverage gaps and the full evidence/assessment trail. Incomplete work can be exported with its gaps visible. Keep source documents separately.</p><button className="primary-button" disabled={busy} onClick={() => { try { downloadEvidenceReport(preparationReport(value, records, links, separate, sources, importIssues), 'taxprep-preparation-2025-26.html'); onMessage('Preparation handover downloaded. It is incomplete tax work; source files are not embedded.') } catch { onMessage('Download failed. Please try again.') } }}>Download preparation handover</button></div>
  </section>
}
