import { taxPosition } from '../tax-position/taxPosition'
import { taxPositionReport } from '../tax-position/taxPositionReport'
import { money, type Evidence, type EvidenceLink } from '../documents/evidence'
import type { DocumentSource } from '../documents/documentReader'
import { evidenceReport } from '../documents/evidenceReport'
import { incomeAmount, PREPARATION_VERSION, preparationSummary, situationQuestions, type Answer, type IncomeFields, type Preparation } from './preparation'
import { GUIDANCE_CHECKED_AT, incomeGuidance } from './guidance'
const escape = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]!)
const answer = (value: Answer) => ({ '': 'Unanswered', yes: 'Yes', no: 'No', unsure: 'Unsure' })[value]
const amount = (value: string) => { const cents = incomeAmount(value); return cents === null ? `${escape(value || 'Blank')} (unresolved)` : money(cents) }
const facts = (value: IncomeFields) => `<p>${value.kind === 'salary' ? 'Salary/wages' : 'Australian bank interest'} · ${escape(value.payer || 'Payer missing')}<br>Reference: ${escape(value.reference || 'Missing')}<br>Year: ${escape(value.year)}<br>Gross: ${amount(value.gross)}<br>Tax withheld: ${amount(value.withheld)}<br>Annual source finalised: ${answer(value.finalised)}${value.kind === 'interest' ? `<br>Sole owner: ${answer(value.soleOwner)}` : ''}</p>`
export function preparationReport(prep: Preparation, records: Evidence[], links: EvidenceLink[], separate: string[], sources: DocumentSource[], importIssues: string[]) {
  const summary = preparationSummary(prep, records, links, separate, importIssues)
  const intro = `<section><h2>Preparation overview</h2><p>Version ${PREPARATION_VERSION}. Draft handover; not ready to lodge. Inputs stay separate from unreviewed tax conclusions.</p><dl><dt>Recorded gross income</dt><dd>${summary.income.included ? money(summary.income.grossCents) : 'Not reviewed'}</dd><dt>Recorded tax withheld</dt><dd>${summary.income.included ? money(summary.income.withheldCents) : 'Not reviewed'}</dd><dt>Illustrative phone work portions</dt><dd>${summary.illustrationCount ? money(summary.illustrativeCents) : 'Not assessed'} · not approved deductions</dd></dl><p>${summary.income.included} of ${prep.income.length} income records included. ${summary.income.complete ? 'Salary/wage and bank-interest list confirmed by the user.' : 'Partial subtotal: the income list is incomplete or unreviewed.'} This is not total taxable income. Tax withheld is not a refund estimate. See the separate fictional calculation and its scope checks below; no reliable refund/payable estimate is issued.</p><h2>What still needs attention</h2><ul>${summary.gaps.map(gap => `<li><strong>${gap.section}:</strong> ${escape(gap.message)}</li>`).join('')}</ul><h2>Income records</h2>${summary.income.items.map(({ item, included, issues }) => `<article><h3>${escape(item.payer || 'Unnamed income source')}</h3><p>${item.origin === 'sample' ? 'Synthetic sample, not ATO pre-fill' : 'Manually entered by the user'} · ${included ? 'Included in recorded totals' : 'Excluded from recorded totals'} · Source reviewed: ${item.reviewed ? 'Yes' : 'No'}</p>${facts(item)}${item.original ? `<details><summary>Original sample values</summary>${facts(item.original)}</details>` : ''}<ul>${issues.map(issue => `<li>${escape(issue)}</li>`).join('')}</ul></article>`).join('')}<p>All salary/wage and bank-interest records added: ${answer(prep.incomeComplete)}.</p><h3>Separate-record decisions</h3><ul>${prep.separate.map(pair => { const ids = pair.split('|'); return `<li>${ids.map(id => { const item = prep.income.find(row => row.id === id); return escape(item ? `${item.payer} · ${item.reference}` : 'Removed record') }).join(' / ')}: user confirmed these are separate income records.</li>` }).join('')}</ul><h2>Situation and coverage</h2><ul>${situationQuestions.map(question => `<li>${escape(question.label)} <strong>${answer(prep.situation[question.key])}</strong></li>`).join('')}</ul><h3>Handover notes</h3><pre>${escape(prep.notes || 'No additional notes.')}</pre><h3>Input guidance</h3><p>Checked ${GUIDANCE_CHECKED_AT} for 2025–26. These references explain inputs; this report does not provide complete myTax field mapping.</p><ul>${incomeGuidance.map(source => `<li><a href="${escape(source.url)}">${escape(source.title)}</a></li>`).join('')}</ul></section>`
  return evidenceReport(records, links, separate, sources, 'Employee preparation handover with recorded income; phone-service expense examples only', importIssues, { title: 'Xoba Paycheck preparation handover', introduction: intro + taxPositionReport(taxPosition(prep, records.length, importIssues)) })
}
