import {useEffect,useRef,useState} from 'react'
import {readStatement} from './statementReader'
import type {Statement} from './statementParser'
import {analyse,type Reviews} from './statementAnalysis'
import {downloadStatementReport,formatAud,statementReport} from './statementReport'
import {downloadYearEndHandoff,financialYearForRange} from '../handoff/yearEndHandoff'
import {buildStatementYearEndHandoff} from './statementHandoff'
import StatementCharts from './StatementCharts'
import StatementTransactions from './StatementTransactions'
export default function StatementDashboard(){
 const[statement,setStatement]=useState<Statement|null>(null),[reviews,setReviews]=useState<Reviews>({}),[from,setFrom]=useState(''),[to,setTo]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
 const[assist,setAssist]=useState(false)
 const sampling=useRef(false),controller=useRef<AbortController|null>(null),mounted=useRef(true),working=useRef(false),input=useRef<HTMLInputElement>(null)
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;controller.current?.abort()}},[])
 async function read(file:File){
  if(working.current)return
  working.current=true;const abort=new AbortController();controller.current=abort;setBusy(true);setError('');setMessage('Reading statement…')
  const timeout=setTimeout(()=>abort.abort(),assist?300000:60000)
  try{const result=await readStatement(file,abort.signal,text=>{if(mounted.current)setMessage(text)},assist&&!sampling.current);if(!mounted.current||abort.signal.aborted)return;setStatement(result);setReviews({});setFrom(result.from);setTo(result.to);setMessage(`${result.rows.length} transactions read. ${result.format==='assisted-read-v1'?'Read by a model, and every transaction adds up to the statement’s own balances.':result.reconciled?'Statement balances match.':'CSV totals have no balance check.'}`)}catch(e){if(mounted.current){setError(abort.signal.aborted?'Reading cancelled. Your previous statement is unchanged.':e instanceof Error?e.message:'The statement could not be read.');setMessage('')}}finally{clearTimeout(timeout);working.current=false;controller.current=null;if(mounted.current){setBusy(false);if(input.current)input.current.value=''}}
 }
 async function sample(){if(working.current)return;sampling.current=true;try{const response=await fetch('/samples/statement.json');if(!response.ok)throw new Error();const{pdfBase64}=await response.json();const bytes=Uint8Array.from(atob(pdfBase64),c=>c.charCodeAt(0));await read(new File([bytes],'fictional-statement.pdf',{type:'application/pdf'}))}catch{setError('The example could not be loaded. Try again.')}finally{sampling.current=false}}
 const valid=!!statement&&!!from&&!!to&&from<=to&&from>=statement.from&&to<=statement.to
 const rows=valid?statement.rows.filter(r=>r.date>=from&&r.date<=to):[],a=analyse(rows,reviews)
 return <section className="statement-dashboard" aria-labelledby="statement-title"><div className="statement-title-row"><div><p className="eyebrow">Understand your money</p><h1 id="statement-title">{statement?'Statement overview':'Your statements, made clear.'}</h1><p>{statement?statement.name:'Turn a supported bank statement into clear totals, categories and a reviewable report.'}</p></div><span className="local-badge"><span aria-hidden="true">●</span> Processed on your device</span></div>
 <div className={`statement-upload ${statement?'compact':''}`}><div className="upload-symbol" aria-hidden="true">↥</div><div><h3>{statement?'Read another statement':'Add a bank statement'}</h3><p>CommBank PDF with selectable text, up to 60 pages, or CSV from any bank. One statement at a time · 10 MB maximum.</p>{statement&&<p className="chart-note">A successful import replaces this session and its reviews. Download your report first.</p>}<label className="pay-assist-choice statement-assist-choice">
   <input type="checkbox" checked={assist} disabled={busy} onChange={e=>setAssist(e.target.checked)}/>
   <span>
    <strong>Read a layout we don’t support</strong>
    <small>
     Only for a PDF this app cannot read on its own. The text of your statement — every transaction description, so every merchant you paid — is sent to our server to be transcribed. The file itself never leaves this device, and neither the file nor its text is stored.
     What comes back is imported only if it adds up exactly to the opening balance, closing balance and totals your statement prints. If it does not, nothing is imported.
     Leave this off and an unsupported layout is simply not read: use your bank’s CSV export, which needs nothing sent anywhere.
    </small>
   </span>
  </label>
  <label className="statement-file">{statement?'Replace statement':'Choose statement'}<input ref={input} aria-label="Choose bank statement" type="file" accept=".pdf,.csv" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void read(file)}}/></label><button className="secondary-button" disabled={busy} onClick={()=>void sample()}>Try example statement</button>{busy&&<button className="text-button" onClick={()=>controller.current?.abort()}>Cancel reading</button>}</div>{!statement&&<ol className="statement-how"><li><span>01</span><div><strong>Read the statement</strong><p>Dates, descriptions and amounts.</p></div></li><li><span>02</span><div><strong>Check the numbers</strong><p>Compare PDF transactions with printed balances.</p></div></li><li><span>03</span><div><strong>Explore and review</strong><p>Correct categories and flag questions.</p></div></li></ol>}</div>
 <p role="status" className="statement-status">{message}</p>{error&&<p role="alert" className="statement-error">{error}</p>}
 {!statement&&<details className="statement-help"><summary>Supported files and privacy</summary><p>PDF support covers the native-text CommBank Date / Transaction / Debit / Credit / Balance layout. Scanned PDFs and other layouts need a bank CSV export. CSV headings: Date,Description,Amount. Dates: YYYY-MM-DD or DD/MM/YYYY. Negative amounts mean money out; positive means money in.</p><p>Files are read in this browser tab, with no document upload, external AI service or saved history. Switching workspaces or refreshing clears the session. The public example uses fictional data. This analysis does not calculate deductions or tax.</p></details>}
 {statement&&<><div className="statement-period"><div><strong>{statement.reconciled?'✓ Statement balances match':'CSV · balance check unavailable'}</strong><p>{statement.rows.length} transactions in the complete statement · {statement.from} to {statement.to}</p></div><div className="statement-date-fields"><label>From date<input type="date" min={statement.from} max={statement.to} value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To date<input type="date" min={statement.from} max={statement.to} value={to} onChange={e=>setTo(e.target.value)}/></label></div></div>{!valid&&<p role="alert" className="statement-error">Choose a valid date range within the statement period.</p>}
 <div className="statement-metrics" aria-label="Statement totals"><div className="metric-feature"><span>Money received</span><strong>{valid?formatAud(a.credits):'—'}</strong><small>Credits · includes transfers and refunds</small></div><div><span>Money out</span><strong>{valid?formatAud(a.debits):'—'}</strong><small>Debits · includes transfers and repayments</small></div><div><span>Net movement</span><strong>{valid?formatAud(a.net):'—'}</strong><small>Money received minus money out</small></div><div><span>Transactions</span><strong>{valid?rows.length:'—'}</strong><small>{a.flagged} flagged for work review</small></div></div>
 <StatementCharts rows={rows} reviews={reviews}/><div className="statement-insights"><section className="statement-panel"><div className="panel-heading"><h3>Possible recurring payments</h3><span>Check these</span></div>{a.recurring.length?<ul>{a.recurring.slice(0,8).map(r=><li key={r.name}><div><strong>{r.name}</strong><small>{r.cadence} · {r.count} payments</small></div><strong>{formatAud(r.cents)}</strong></li>)}</ul>:<p className="empty-note">No clear repeating pattern in this period. That does not rule out subscriptions.</p>}<p className="chart-note">Similar amounts and timing suggest a pattern, not a confirmed subscription.</p></section><section className="statement-panel review-callout"><p className="eyebrow">Make it your own</p><h3>A few things to check</h3><p><strong>{a.uncategorised}</strong> transactions need a clearer category.</p><p><strong>{a.similar}</strong> entries look similar to another payment. They remain counted because the statement includes them.</p><p>Open a transaction to correct its category, mark it personal or flag it for work review.</p></section></div>
 <StatementTransactions key={statement.id+from+to} statement={statement} rows={rows} reviews={reviews} onChange={setReviews}/>
 <details className="statement-help"><summary>Statement checks and processing details</summary><p>Complete statement opening: {statement.opening===null?'not supplied':formatAud(statement.opening)}. Closing: {statement.closing===null?'not supplied':formatAud(statement.closing)}. PDF totals are checked before import; CSV has no bank balance reconciliation.</p><p>Posting dates control the period. Value dates remain in the descriptions. Categories use merchant-description rules and can be corrected. No tax eligibility assessment is made. {statement.format==='assisted-read-v1'?'This statement’s layout is not one this app documents, so you asked for its text to be transcribed by a model; every transaction was then checked against the balances the statement prints. Nothing was stored, and the file never left this device.':'No AI model was used to read this statement.'}</p><ul>{statement.notices.map((n,i)=><li key={i}>{n}</li>)}</ul><p>Reading happens in this tab. No statement is uploaded or saved. Switching workspaces or refreshing clears the session.</p></details>
 <div className="statement-export"><div><h3>Take the useful part with you.</h3><p>Download the detailed report, or a small year-end handoff containing only coverage counts, review totals and the source hash. The handoff does not include transaction descriptions.</p>{valid&&!financialYearForRange(from,to)&&<p className="chart-note">Choose dates within one Australian financial year before exporting a year-end handoff.</p>}</div><div><button className="primary-button" disabled={!valid||busy} onClick={()=>{downloadStatementReport(statementReport(statement,reviews,from,to));setMessage('Statement report downloaded. Keep your original statement separately.')}}>Download statement report</button><button className="secondary-button" disabled={!valid||busy||!financialYearForRange(from,to)} onClick={()=>{try{const handoff=buildStatementYearEndHandoff(statement,reviews,from,to);downloadYearEndHandoff(handoff,'taxprep-bank-spending-handoff.json');setMessage('Year-end handoff downloaded. It contains summary coverage and source hashes, not transaction descriptions.')}catch(error){setError(error instanceof Error?error.message:'Year-end handoff could not be created.')}}}>Download year-end handoff</button><button className="text-button" disabled={busy} onClick={()=>{setStatement(null);setReviews({});setFrom('');setTo('');setMessage('Statement and reviews cleared.');setError('')}}>Clear statement</button></div></div></>}
 </section>
}
